export const QUERY_KEYS = {
  ASSETS_QUERY: 'ASSETS_QUERY',
  COLLECTIONS_QUERY: 'COLLECTIONS_QUERY',
  MY_COLLECTIONS_QUERY: 'MY_COLLECTIONS_QUERY',
  MY_ASSETS_QUERY: 'MY_ASSETS_QUERY',
  NFTS: 'NFTS',
  NFT: 'NFT',
  BANNER: 'BANNER',
  CATEGORIES: 'CATEGORIES',
  COLLECTIONS: 'COLLECTIONS',
  ADDRESS: 'ADDRESS',
};
