export const ASSETS_QUERY = 'GET_ASSETS';
export const COLLECTIONS_QUERY = 'GET_COLLECTIONS';
export const MY_COLLECTIONS_QUERY = 'GET_MY_COLLECTIONS';
export const MY_ASSETS_QUERY = 'GET_MY_ASSETS';
export const NFTS = 'NFTS';
